Dev
AndrasNemeth94/IMDBfrontend pull request #1
Opened 2020-08-24 18:19 UTC by AndrasNemeth94

@zsdominik  úgy néz ki működik :D

2020-08-24 18:39 UTC, zsdominik requested changes
Please format the code correctly. Otherwise there is not much logic here yet. I think this will be good after you fix the format.

2020-08-24 18:39 UTC, zsdominik commented on src/App.css
> +}*/
Please remove this if you don't use them or if you use them then remove the comment.

https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

2020-08-24 18:39 UTC, zsdominik commented on src/view/Footer.css
> +
remove the exra line pls

2020-08-24 18:39 UTC, zsdominik commented on src/view/Footer.js
> +export default Footer;
I think we can remove the unnecessary extra lines and please format the code correctly. Use Prettify or Eslint and set up the "Format on save" option in VSCode

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

2020-08-24 18:39 UTC, zsdominik commented on src/view/Header.css
> +
Extra line

2020-08-24 18:39 UTC, zsdominik commented on src/view/Header.js
> +export default Header;
Same here with the formatter

2020-08-24 18:39 UTC, zsdominik commented on src/view/Main.js
> +export default Main;
Same here with the formatter

2020-08-26 20:01 UTC, AndrasNemeth94 reviewed
Thank you for the advice, I'll work on it

2020-08-27 10:08 UTC, zsdominik requested changes

2020-08-27 10:08 UTC, zsdominik commented on src/img/LoMLM.svg
> +>>>>>>> 922b61a62dd7ad20bedb5e65b71b6c6c383bc722
You did not resolve merge conflicts here and above inside this file.  Right now the code containing syntax errors and I'm pretty sure you are not able to display this svg correctly.

2020-08-27 10:08 UTC, zsdominik commented on src/App.js
> +}
Sorry for the nitpicking about this but I think this tabulation is too much. In my opinion 2 or 4 spaces are enough.

check this example:
https://github.com/gothinkster/react-redux-realworld-example-app/blob/master/src/components/Editor.js#L95

2020-08-27 10:08 UTC, zsdominik commented on src/view/Footer.css
> +p{
a space is missing after the p

2020-08-27 10:08 UTC, zsdominik commented on src/view/Footer.js
> +		return (
check the comment above about the indentation

2020-08-27 10:08 UTC, zsdominik commented on src/view/Header.js
> +			</ReactBootStrap.Navbar>
check the comment above about the indentation

2020-08-27 10:08 UTC, zsdominik commented on src/view/Main.js
> +	}
check the comment above about the indentation

2020-10-04 16:03 UTC, closed without merging